"""Articles, Categories, Users, ArticlesCategoriesAssociations tables.

Revision ID: a49e7b6f6101
Revises:
Create Date: 2025-02-16 08:46:19.084483+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a49e7b6f6101"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("oid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.PrimaryKeyConstraint("oid"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "articles",
        sa.Column("author_oid", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["author_oid"],
            ["users.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_table(
        "article_category_associations",
        sa.Column("article_oid", sa.Uuid(), nullable=False),
        sa.Column("category_oid", sa.Uuid(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_oid"],
            ["articles.oid"],
        ),
        sa.ForeignKeyConstraint(
            ["category_oid"],
            ["categories.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
        sa.UniqueConstraint(
            "article_oid", "category_oid", name="unique_category_for_article"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article_category_associations")
    op.drop_table("articles")
    op.drop_table("users")
    op.drop_table("categories")
    # ### end Alembic commands ###
