---
networks:
  backend:
    driver: bridge
services:
  articles-platform:
    container_name: articles-platform
    build:
      context: .
      dockerfile: Dockerfile
    image: articles-platform-image
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - path: .default.env
        required: false
      - path: .env
        required: false
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL:-}
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    networks:
      - backend
    entrypoint:
      - pwd
